# Generated by Django 2.2.5 on 2020-02-13 00:53

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='surfType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(max_length=40)),
                ('country', models.CharField(blank=True, max_length=30)),
                ('board_type', models.CharField(choices=[('Long', 'Long'), ('short', 'short'), ('fish', 'fish'), ('egg', 'egg')], max_length=20)),
                ('board_length', models.CharField(choices=[("6'", "6'"), ('6\'-6"', '6\'-6"'), ("7'", "7'"), ('7\'-6"', '7\'-6"'), ("8'", "8'"), ('8\'-6"', '8\'-6"'), ("9'", "9'"), ('9\'-6"', '9\'-6"'), ("10'", "10'"), ('10\'-6"', '10\'-6"'), ("11'", "11'"), ('SUP', 'SUP')], max_length=20)),
            ],
            managers=[
                ('surfTypes', django.db.models.manager.Manager()),
            ],
        ),
    ]
