# Generated by Django 2.2.5 on 2020-02-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('F', 'Fiction'), ('NF', 'Nonfiction')], max_length=10)),
                ('genre', models.CharField(max_length=30)),
                ('rating', models.CharField(choices=[('Loved it', 'Loved it'), ('Liked it', 'Liked it'), ('Tolerated it', 'Tolerated it'), ('Hated it', 'Hated it')], max_length=15)),
            ],
        ),
    ]
