# Generated by Django 2.2.5 on 2020-02-19 16:58

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('BookBag', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='book',
            managers=[
                ('Books', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='type',
            field=models.CharField(choices=[('Fiction', 'Fiction'), ('Nonfiction', 'Nonfiction')], max_length=10),
        ),
    ]
