# Generated by Django 2.2.5 on 2020-02-21 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookBag', '0002_auto_20200219_0858'),
        ('BookBag', '0002_auto_20200218_1848'),
    ]

    operations = [
    ]
