# Generated by Django 2.2.5 on 2020-02-12 20:06

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmiiboFigure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('gameSeries', models.CharField(max_length=60)),
                ('purchasePrice', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('purchaseDate', models.CharField(blank=True, max_length=60, null=True)),
                ('amount', models.PositiveSmallIntegerField()),
            ],
            managers=[
                ('AmiiboFigurines', django.db.models.manager.Manager()),
            ],
        ),
    ]
