# Generated by Django 2.2.5 on 2020-02-12 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Amiibo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amiibofigure',
            old_name='gameSeries',
            new_name='game_series',
        ),
        migrations.RenameField(
            model_name='amiibofigure',
            old_name='purchaseDate',
            new_name='purchase_date',
        ),
        migrations.RenameField(
            model_name='amiibofigure',
            old_name='purchasePrice',
            new_name='purchase_price',
        ),
    ]
