# Generated by Django 2.2.5 on 2020-02-12 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amiibo', '0002_auto_20200212_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amiibofigure',
            name='amount',
            field=models.PositiveSmallIntegerField(blank=True, default=1),
        ),
    ]
