# Generated by Django 2.2.5 on 2020-02-12 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amiibo', '0004_auto_20200212_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amiibofigure',
            name='amount',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=1),
        ),
    ]
