# Generated by Django 2.2.5 on 2019-11-12 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FootyDemo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jersey',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
