# Generated by Django 2.2.5 on 2020-02-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=30)),
                ('station_frequency', models.DecimalField(decimal_places=1, max_digits=4)),
                ('genre', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('station_url', models.URLField(default='http://', max_length=300)),
            ],
        ),
    ]
