# Generated by Django 2.2.5 on 2020-02-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommunityFM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='station_url',
            field=models.URLField(default='http://', max_length=300),
        ),
    ]
