# Generated by Django 2.2.5 on 2020-02-13 22:42

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('position', models.CharField(choices=[('Point Guard', 'Point Guard'), ('Shooting Guard', 'Shooting Guard'), ('Small Forward', 'Small Forward'), ('Power Forward', 'Power Forward'), ('Center', 'Center')], max_length=75)),
                ('currentStatus', models.CharField(choices=[('Current Player', 'Current Player'), ('Retired', 'Retired'), ('Plays for another team', 'Plays for another team')], max_length=75)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
            ],
            managers=[
                ('Players', django.db.models.manager.Manager()),
            ],
        ),
    ]
