# Generated by Django 2.2.5 on 2020-02-18 17:52

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('BookShelf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='shelfitem',
            managers=[
                ('ShelfItems', django.db.models.manager.Manager()),
            ],
        ),
    ]
